
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bookstore_api_development
  username: postgres
  password: 456321

  
test:
  <<: *default
  database: bookstore_api_test
  username: postgres
  password: 456321

production:
  <<: *default
  database: bookstore_api_production
  username: postgres
  password: 456321
